# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganancia',
            name='balance',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ganancia',
            name='ganancia',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ganancia',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
