# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170814_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='gain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('balance', models.DecimalField(decimal_places=10, max_digits=19)),
                ('profit', models.DecimalField(decimal_places=10, max_digits=19)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='ganancia',
        ),
    ]
