# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.DeleteModel(
            name='config',
        ),
    ]
