# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170814_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
